name: Deploy

on:
  push:
    branches:
      - main

env:
  NODE_ENV: production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
      - name: Update corepack
        run: npm install -g corepack@latest
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - name: Deploy
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          quiet: true
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
